OPTIONS (SKIP=1)
LOAD DATA
INTO TABLE "OE"."INVENTORIES"
APPEND
FIELDS CSV WITH EMBEDDED
TRAILING NULLCOLS
   (PRODUCT_ID                     FLOAT EXTERNAL
   ,WAREHOUSE_ID                   FLOAT EXTERNAL
   ,QUANTITY_ON_HAND               FLOAT EXTERNAL
   )
