OPTIONS (SKIP=1)
LOAD DATA
APPEND INTO TABLE "ODBCAPTURE"."BUILD_PATH"
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
   (PARENT_BUILD_SEQ               FLOAT EXTERNAL
   ,BUILD_SEQ                      FLOAT EXTERNAL
   )
