OPTIONS (SKIP=1)
LOAD DATA
APPEND INTO TABLE "ODBCAPTURE"."TSPACE_CONF"
FIELDS CSV WITH EMBEDDED
TRAILING NULLCOLS
   (USERNAME                       CHAR(128)
   ,TSPACE_NAME                    CHAR(30)
   ,TS_QUOTA                       CHAR(10)
   )
