OPTIONS (SKIP=1)
LOAD DATA
INTO TABLE "ODBCAPTURE"."USER_DEFINED_TYPE_CONF"
APPEND
FIELDS CSV WITH EMBEDDED
TRAILING NULLCOLS
   (TYPE_NAME                      CHAR(128)
   ,PACKAGE_NAME                   CHAR(128)
   )
