OPTIONS (SKIP=1)
LOAD DATA
APPEND INTO TABLE "ODBCAPTURE"."USER_DEFINED_TYPE_CONF"
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
   (TYPE_NAME                      CHAR(128)
   ,PACKAGE_NAME                   CHAR(128)
   )
