OPTIONS (SKIP=1)
LOAD DATA
INTO TABLE "HR"."COUNTRIES"
APPEND
FIELDS CSV WITH EMBEDDED
TRAILING NULLCOLS
   (COUNTRY_ID                     CHAR(2)
   ,COUNTRY_NAME                   CHAR(60)
   ,REGION_ID                      FLOAT EXTERNAL
   )
