OPTIONS (SKIP=1)
LOAD DATA
APPEND INTO TABLE "HR"."COUNTRIES"
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
   (COUNTRY_ID                     CHAR(2)
   ,COUNTRY_NAME                   CHAR(60)
   ,REGION_ID                      FLOAT EXTERNAL
   )
