OPTIONS (SKIP=1)
LOAD DATA
APPEND INTO TABLE "HR"."DEPARTMENTS"
FIELDS CSV WITH EMBEDDED
TRAILING NULLCOLS
   (DEPARTMENT_ID                  FLOAT EXTERNAL
   ,DEPARTMENT_NAME                CHAR(30)
   ,MANAGER_ID                     FLOAT EXTERNAL
   ,LOCATION_ID                    FLOAT EXTERNAL
   )
