OPTIONS (SKIP=1)
LOAD DATA
APPEND INTO TABLE "HR"."JOBS"
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
   (JOB_ID                         CHAR(10)
   ,JOB_TITLE                      CHAR(35)
   ,MIN_SALARY                     FLOAT EXTERNAL
   ,MAX_SALARY                     FLOAT EXTERNAL
   )
