OPTIONS (SKIP=1)
LOAD DATA
APPEND INTO TABLE "HR"."REGIONS"
FIELDS CSV WITH EMBEDDED
TRAILING NULLCOLS
   (REGION_ID                      FLOAT EXTERNAL
   ,REGION_NAME                    CHAR(25)
   )
