OPTIONS (SKIP=1)
LOAD DATA
APPEND INTO TABLE "OE"."CATEGORIES_TAB"
FIELDS CSV WITH EMBEDDED
TRAILING NULLCOLS
   (CATEGORY_NAME                  CHAR(50)
   ,CATEGORY_DESCRIPTION           CHAR(1000)
   ,CATEGORY_ID                    FLOAT EXTERNAL
   ,PARENT_CATEGORY_ID             FLOAT EXTERNAL
   )
