OPTIONS (SKIP=1)
LOAD DATA
APPEND INTO TABLE "OE"."INVENTORIES"
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
   (PRODUCT_ID                     FLOAT EXTERNAL
   ,WAREHOUSE_ID                   FLOAT EXTERNAL
   ,QUANTITY_ON_HAND               FLOAT EXTERNAL
   )
