
--
--  Create OE.LINEITEM_T Type
--

set define off


--DBMS_METADATA:OE.LINEITEM_T

  CREATE OR REPLACE EDITIONABLE TYPE "OE"."LINEITEM_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","ITEMNUMBER" NUMBER(38),"DESCRIPTION" VARCHAR2(256 CHAR),"PART" "PART_T")NOT FINAL INSTANTIABLE 
/


--  Grants


--  Synonyms


set define on
