OPTIONS (SKIP=1)
LOAD DATA
INTO TABLE "OE"."PRODUCT_DESCRIPTIONS"
APPEND
FIELDS CSV WITH EMBEDDED
TRAILING NULLCOLS
   (PRODUCT_ID                     FLOAT EXTERNAL
   ,LANGUAGE_ID                    CHAR(3)
   ,TRANSLATED_NAME                CHAR(250) "UNISTR(to_char(:TRANSLATED_NAME))"
   ,TRANSLATED_DESCRIPTION         CHAR(10000) "UNISTR(to_char(:TRANSLATED_DESCRIPTION))"
   )
