OPTIONS (SKIP=1)
LOAD DATA
APPEND INTO TABLE "OE"."PRODUCT_DESCRIPTIONS"
FIELDS CSV WITH EMBEDDED
TRAILING NULLCOLS
   (PRODUCT_ID                     FLOAT EXTERNAL
   ,LANGUAGE_ID                    CHAR(3)
   ,TRANSLATED_NAME                CHAR(50)
   ,TRANSLATED_DESCRIPTION         CHAR(2000)
   )
