OPTIONS (SKIP=1)
LOAD DATA
APPEND INTO TABLE "OE"."PROMOTIONS"
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
   (PROMO_ID                       FLOAT EXTERNAL
   ,PROMO_NAME                     CHAR(20)
   )
