
--
--  Create OE.REJECTION_T Type
--

set define off


--DBMS_METADATA:OE.REJECTION_T

  CREATE OR REPLACE EDITIONABLE TYPE "OE"."REJECTION_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","REJECTED_BY" VARCHAR2(10 CHAR),"DATE_REJECTED" DATE,"REASON_REJECTED" VARCHAR2(2048 CHAR))NOT FINAL INSTANTIABLE
/


--  Grants


--  Synonyms


set define on
